name: Update current INE references
on:
  schedule:
    - cron: '15 * * * *'
jobs:
  update_refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: bash update_data.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
