name: Check INE references in OSM
on:
  schedule:
    - cron: '6 * * * *'
jobs:
  update_refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: bash update_data.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Update data
      - uses: actions/deploy-pages@v1
        # if: steps.auto-commit-action.outputs.changes_detected == 'true'        
