name: Check INE references in OSM
on:
  schedule:
    - cron: '0 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  pages: write
  id-token: write
  contents: write
jobs:
  update_refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: bash update_data.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Update data
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - uses: actions/deploy-pages@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
